name: Test Wheels

on:  workflow_dispatch

jobs:
  test_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ 3.7, 3.8, 3.9 ]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout empyrical
        uses: actions/checkout@v3

      - name: Install wheel & run tests
        run: |
          pip install -U pip wheel tox-gh-actions
          pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple your-package empyrical-reloaded[test]
          tox -p auto -q
